//
//  Colors.swift
//  RCRC
//
//  Created by Errol on 22/10/20.
//

import UIKit

enum Colors {
    static let green = UIColor(hexString: "#006F44", alpha: 1.0)
    static let backgroundGray = UIColor(hexString: "#EFEFF4", alpha: 1.0)
    static let searchBarGray = UIColor(hexString: "#EAEAEB", alpha: 1.0)
    static let popupGray = UIColor(hexString: "#FFFFF0", alpha: 1.0)
    static let availableRouteBottomViewGray = UIColor(hexString: "#F4F4F4", alpha: 1.0)
    static let black = UIColor(hexString: "#000000", alpha: 1.0)
    static let white = UIColor(hexString: "#FFFFFF", alpha: 1.0)
    static let orange = UIColor(hexString: "#FF9436", alpha: 1.0)
    static let lightFontGray = UIColor(hexString: "#8A8D8F", alpha: 1.0)
    static let locationMarkerBlue = UIColor(hexString: "#00A3DD", alpha: 1.0)
    static let locationMarkerLightGreen = UIColor(hexString: "#39FF14", alpha: 1.0)
    static let borderColorGray = UIColor(hexString: "#A1A1A1", alpha: 1.0)
    static let weatherBlue = UIColor(hexString: "#397AD3", alpha: 1.0)
    static let weatherYellow = UIColor(hexString: "#FFDB12", alpha: 1.0)
    static let weatherOrange = UIColor(hexString: "#F07729", alpha: 1.0)
    static let weatherRed = UIColor(hexString: "#EB0008", alpha: 1.0)
    static let dialogBackground = UIColor(hexString: "#EFEFF4", alpha: 0.7)
    static let red = UIColor(hexString: "#EB0008", alpha: 1.0)
    static let shadowGray = UIColor(hexString: "#000000", alpha: 0.6)
    static let searchBarGrayNew = UIColor(hexString: "#8E8E93", alpha: 0.12)
    static let tableViewHeader = UIColor(hexString: "#EFEFF4", alpha: 1.0)
    static let searchPinGray = UIColor(hexString: "#E1E1E1", alpha: 1.0)
    static let lightGreen = UIColor(hexString: "#C4DB6F", alpha: 1.0)
    static let lightYellow = UIColor(hexString: "#FED107", alpha: 1.0)
    static let reportIncidenceLightGray = UIColor(hexString: "#DFDFE2", alpha: 1.0)
    static let busRouteGreen = UIColor(hexString: "#5FBB68", alpha: 1.0)
    static let walkRouteGray = UIColor(hexString: "#828282", alpha: 1.0)
    static let darkGray = UIColor(hexString: "#737373", alpha: 1.0)
    static let borderGreen = UIColor(hexString: "#5DD02B", alpha: 1.0)
    static let mapWalkingGray = UIColor(hexString: "#828282")
    static let mapBusGreen = UIColor(hexString: "#5FBB68")
    static let tripBusGreen = UIColor(hexString: "#3FAE49")
    static let textGray = UIColor(hexString: "#606060")
    static let defaultWeatherBackground = UIColor(hexString: "#FF9436")
    static let textFieldBorder = UIColor(hexString: "#BEBEBE")
    static let viewBackground = UIColor(patternImage: UIImage(named: "backgrround_logo") ?? UIImage())
    static let pickerBackground = UIColor(hexString: "#F8F8F8")
    static let noFavoritesText = UIColor(hexString: "#A9A9A9")
    static let yourCurrentLocationBlue = UIColor(hexString: "#00A3DD")
    static let headerColor = UIColor(hexString: "#8fdbb5")
    static let buttonHyperLink = UIColor(hexString: "#00A3DD")
    
    static let rptTrafficWhite = UIColor(hexString: "#FFFFFF")
    static let rptGreen = UIColor(hexString: "#3CD52E")
    static let rptNeonGreen = UIColor(hexString: "#3AFF17")
    static let rptGrey = UIColor(hexString: "#737373")
    static let rptDarkGreen = UIColor(hexString: "#123108")
    static let rptHeaderTitle = UIColor(hexString: "#006F44")
    static let rptNavButtonGreen = UIColor(hexString: "#5EAE32")
    static let rptNavBackground = UIColor(hexString: "#123108")
    static let rptArrowGrey = UIColor(hexString: "#E8E8E8")
    static let rptOnBoardingHeaderTitle = UIColor(hexString: "#123108")
    static let yourCurrentLocationGreen = UIColor(hexString: "#5EAE32")
    static let buttonTintColor = UIColor(hexString: "#5EAE32")
    static let tableErrorTextColor = UIColor(hexString: "#606060")
    static let tableDividerColor = UIColor(hexString: "#707070")
    static let ptIconTintColor = UIColor(hexString: "#50CC1A")
    static let tripBusLineColor = UIColor(hexString: "#606060")
    static let textColor = UIColor(hexString: "#162613")
    static let rptHtmlGrey = UIColor(hexString: "#606060")
    static let newGreen = UIColor(hexString: "#50CC1A")
    static let lightGrey = UIColor(hexString: "#DFE0E1")
    static let textErrorColor = UIColor(hexString: "#FF0000")
    static let textLightColor = UIColor(hexString: "#A9A6A6")
    static let btnGreyTxt = UIColor(hexString: "#989898")
    static let privacyNoticeGray = UIColor(hexString: "#8B8B8B")
    static let placeHolderGray = UIColor(hexString: "#A2A2A2")
    static let northRouteGreen = UIColor(hexString: "CFFDA4")
    static let southRouteGreen = UIColor(hexString: "EBFEDA")
    static let textDarkColor = UIColor(hexString: "#707070")
    static let textColorBlue = UIColor(hexString: "#ff33b5e5")
    
    static let route984 = UIColor(hexString: "#5daa9a")
    static let route953 = UIColor(hexString: "#5daa9a")
    static let route952 = UIColor(hexString: "#5daa9a")
    static let route951 = UIColor(hexString: "#5daa9a")
    static let route941 = UIColor(hexString: "#5daa9a")
    static let route940 = UIColor(hexString: "#5daa9a")
    static let route928 = UIColor(hexString: "#5daa9a")
    static let route730 = UIColor(hexString: "#459CC6")
    static let route680 = UIColor(hexString: "#AA55A1")
    static let route660 = UIColor(hexString: "#F15B5B")
    static let route540 = UIColor(hexString: "#459CC6")
    static let route430 = UIColor(hexString: "#459CC6")
    static let route350 = UIColor(hexString: "#2DA44A")
    static let route342 = UIColor(hexString: "#F15B5B")
    static let route341 = UIColor(hexString: "#2DA44A")
    static let route280 = UIColor(hexString: "#AA55A1")
    static let route250 = UIColor(hexString: "#F15B5B")
    static let route231 = UIColor(hexString: "#2DA44A")
    static let route230 = UIColor(hexString: "#AA55A1")
    static let route181 = UIColor(hexString: "#459CC6")
    static let route180 = UIColor(hexString: "#459CC6")
    static let route170 = UIColor(hexString: "#F15B5B")
    static let route160 = UIColor(hexString: "#2DA44A")
    static let route151 = UIColor(hexString: "#2DA44A")
    static let route150 = UIColor(hexString: "#AA55A1")
    static let route17 = UIColor(hexString: "#459CC6")
    static let route16 = UIColor(hexString: "#2DA44A")
    static let route13 = UIColor(hexString: "#98BB56")
    static let route11 = UIColor(hexString: "#98BB56")
    static let route10 = UIColor(hexString: "#AA55A1")
    static let route9 = UIColor(hexString: "#AA55A1")
    static let route8 = UIColor(hexString: "#2DA44A")
    static let route7 = UIColor(hexString: "#F15B5B")
}
